import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen`}
      >
        <SidebarProvider>
          <div className="flex h-full w-full">
            {/* Sidebar with a fixed width */}
            <AppSidebar className="w-64 bg-gray-100" />

            {/* Main content should take up the rest of the space */}
            <main className="relative flex-1 max-w-full overflow-auto p-6">
              {/* 
                - `relative`: To position the `SidebarTrigger` absolutely within this container.
                - `flex-1`: Ensures the main content area fills the remaining space.
                - `max-w-full`: Makes sure the content can expand to full width.
                - `overflow-auto`: Allows scrolling if the content overflows.
                - `p-6`: Adds padding around the content.
              */}
              {children}

              {/* Sidebar Trigger */}
              <SidebarTrigger
                className="absolute top-4 left-4 z-10"
              />
              {/* 
                - `absolute`: Positions the trigger button relative to the main content.
                - `top-4` and `left-4`: Positions the button within the content area.
                - `z-10`: Ensures the button appears on top of other content.
              */}
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
